import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { FloatingWhatsApp } from 'react-floating-whatsapp'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        {children}
        <FloatingWhatsApp phoneNumber="+923149884064" accountName="AH Fabrics"/>
        </body>
    </html>
  );
}
